### ISSUE TITLE
Invalid option value "true" for rule "scss/at-import-partial-extension"

### ISSUE THREAD

**Issue by makenowjust** [xojs/stylelint-config-xo-scss#1]
# About

Since version `0.10.0`, the following error causes when extending this config:

```
Invalid Option: Invalid option value "true" for rule "scss/at-import-partial-extension"
```

## Minimal Reproducible Example

```console
$ mkdir stylelint-config-xo-scss-bug && cd $_
$ yarn add stylelint stylelint-config-xo-scss@0.10.0
$ echo 'module.exports = {extends: "stylelint-config-xo-scss"}' > stylelint.config.js
$ echo '/* for testing */' > test.scss
$ yarn stylelint test.scss
yarn run v1.19.2
warning package.json: No license field
/.../stylelint-config-xo-scss-bug/node_modules/.bin/stylelint test.scss

Invalid Option: Invalid option value "true" for rule "scss/at-import-partial-extension"

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Work Around

Add this line into your `stylelint.config.js`:

```javascript
  rules: {'scss/at-import-partial-extension': 'always'}
```

## Possible Solution

This bug is introduced into https://github.com/xojs/stylelint-config-xo-scss/commit/86e7d26e8d6a57f10d96e11ddd8eb0bf677dc008.

We can easily fix this by modifying option value into `"always"`.
However I wonder why [the test](https://github.com/xojs/stylelint-config-xo-scss/blob/05ecb49d17cf5d74cd20c5950acfff3f6c991371/test/test.js) miss this bug, and I guess the test is broken. It should be fixed.

Thank you :smile:

**Comment by zebapy** [comment]
@sindresorhus Why is this on `always`? Is it not more common to leave the scss extension off of imports?

**Comment by sindresorhus** [comment]
Fixed: https://github.com/xojs/stylelint-config-xo-scss/releases/tag/v0.12.0
