### ISSUE TITLE
Inconsistent rule for 'scss/at-import-partial-extension'

### ISSUE THREAD

**Issue by Tobi-mmt** [xojs/stylelint-config-xo-scss#2]
## Problem
The rule in https://github.com/xojs/stylelint-config-xo-scss/blob/master/index.js#L21 requires an extension for all imports. But the next line prohibites to use the `.scss` extension.

If I want to import e.g some color values from an seperated `color.scss` to an other scss file, then I want to use it like that:

### Minimal Reproducible Example

```scss
@import './color.scss'

body {
    background: $color-silver;
}
```

But the config does not allow this. 
If I **remove** the `scss` extension at the end, the rule `scss/at-import-partial-extension` throws an eror. 
If I **add** the `scss` extension the `scss/at-import-partial-extension-blacklist` rule throws an error.
So it's not possible to solve the errors at this point.

## Possible Solution
IMO it would be more consistent if we delete the `scss/at-import-partial-extension-blacklist`. Then just every import needs the extension.

OR

We modify the `scss/at-import-partial-extension` to something like that (needs extra PR in `stylelint-scss`):

```js
'scss/at-import-partial-extension': ['always', , { "except": ["scss"] }]
```

**Comment by sindresorhus** [comment]
I'm changing it to enforce no extension for Sass files. I wanted to make it explicit that Sass files are used as they share `@import` with plain CSS, so there could be ambiguity, but it seems that decision is unpopular. Also, the future of Sass is `@use` instead, so doesn't really matter.
